name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/tests
  pull_request:
    branches:
      - feature/tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install Flask Faker pytest

    - name: Run tests
      run: |
        pytest app_test.py

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create virtual environment
      run: |
        python -m venv venv
        . venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@0.0.8
      with:
        service-id: ${{ secrets.UTSID }}
        api-key: ${{ secrets.UTSIKEY }}
